# Generated by Django 4.1.7 on 2023-03-13 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('livros', '0001_initial'),
        ('copias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='copy',
            name='books',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='copy', to='livros.book'),
        ),
        migrations.AddField(
            model_name='borrow',
            name='copy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrows', to='copias.copy'),
        ),
    ]
