# Generated by Django 4.1.7 on 2023-03-07 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('copias', '0001_initial'),
        ('livros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='copy',
            name='books',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='livros.book'),
        ),
        migrations.AddField(
            model_name='borrowing',
            name='copies',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copy_borrowed', to='copias.copy'),
        ),
    ]
