# Generated by Django 4.1.7 on 2023-03-11 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0002_initial'),
        ('copias', '0004_alter_copy_books'),
    ]

    operations = [
        migrations.AlterField(
            model_name='copy',
            name='books',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='copy', to='livros.book'),
        ),
    ]
