# Generated by Django 4.1.7 on 2023-03-13 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('number_pages', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('DRAMA', 'Drama'), ('ROMANCE', 'Romance'), ('EPICO', 'Epico'), ('AVENTURA', 'Aventura'), ('DISTOPIA', 'Distopia'), ('CONTO', 'Conto'), ('FANTASIA', 'Fantasia'), ('SOBRENATURAL', 'Sobrenatural'), ('TERROR', 'Terror'), ('NEUTRO', 'Default')], default='NEUTRO', max_length=50)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
