# Generated by Django 4.1.7 on 2023-03-07 18:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('number_pages', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('DRAMA', 'Drama'), ('ROMANCE', 'Romance'), ('EPICO', 'Epico'), ('AVENTURA', 'Aventura'), ('DISTOPIA', 'Distopia'), ('CONTO', 'Conto'), ('FANTASIA', 'Fantasia'), ('SOBRENATURAL', 'Sobrenatural'), ('TERROR', 'Terror'), ('NEUTRO', 'Default')], default='NEUTRO', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Following',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='livros.book')),
            ],
        ),
    ]
